#!/bin/sh -e
#

if ! id | grep -q root; then
	echo "beagle-version must be run as root:"
	echo "sudo beagle-version"
	exit
fi

check_bootloader () {
	if [ -b ${drive}p1 ] ; then
		test_var=$(strings ${drive}p1 | grep 'HSS' | head -n1 || true)
		if [ ! "x${test_var}" = "x" ] ; then
			echo "bootloader:[${drive}p1]:[payload.bin]:[${test_var}]"
		fi
	fi
	if [ -b ${drive}p1 ] ; then
		test_var=$(strings ${drive}p1 | grep 'U-Boot 20' | head -n1 || true)
		if [ ! "x${test_var}" = "x" ] ; then
			echo "bootloader:[${drive}p1]:[u-boot.bin]:[${test_var}]"
		fi
	fi
}

dpkg_check_version () {
	unset pkg_version
	pkg_version=$(dpkg -l | awk '$2=="'$pkg'" { print $3 }' || true)
	if [ ! "x${pkg_version}" = "x" ] ; then
		echo "pkg:[$pkg]:[$pkg_version]"
	else
		echo "WARNING:pkg:[$pkg]:[NOT_INSTALLED]"
	fi
}

dpkg_check_version_replaced () {
	unset pkg_version
	pkg_version=$(dpkg -l | awk '$2=="'$pkg'" { print $3 }' || true)
	if [ ! "x${pkg_version}" = "x" ] ; then
		echo "pkg:[$pkg]:[$pkg_version]:[GOT_REPLACED_BY_NEXT]"
	fi
}

#00000000: 4245 4147 4c45 562d 4649 5245 2d41 302d  BEAGLEV-FIRE-A0-
#00000010: 4d50 4653 3032 3554 0aff ffff ffff ffff  MPFS025T........

if [ -f /sys/bus/i2c/devices/1-0050/eeprom ] ; then
	board_eeprom=$(xxd -p -l 24 /sys/bus/i2c/devices/1-0050/eeprom | xxd -p -r || true)
	echo "eeprom:[${board_eeprom}]"
fi

device_model=$(cat /proc/device-tree/model | sed "s/ /_/g" | tr -d '\000')
echo "model:[${device_model}]"

if [ -f /etc/dogtag ] ; then
	echo "dogtag:[`cat /etc/dogtag`]"
fi

if [ -b /dev/mmcblk0 ] ; then
	drive=/dev/mmcblk0
	check_bootloader
fi

#if [ -b /dev/mmcblk1 ] ; then
#	drive=/dev/mmcblk1
#	check_bootloader
#fi

echo "kernel:[`uname -r`]"

if [ -f /proc/device-tree/chosen/base_dtb ] ; then
	echo "UBOOT: Booted Device-Tree:[`cat /proc/device-tree/chosen/base_dtb`]"
fi
if [ -d /proc/device-tree/chosen/overlays/ ] ; then
	ls /proc/device-tree/chosen/overlays/ -p | grep -v / | grep -v name | sed 's/^/UBOOT: Loaded Overlay:[/' | sed 's/$/]/'
fi

if [ -f /proc/device-tree/chosen/overlays/DEFAULT-CAPE-GATEWARE ] ; then
	version=$(cat /proc/device-tree/chosen/overlays/DEFAULT-CAPE-GATEWARE | head -n1 || true)
	echo "UBOOT: Loaded Overlay:[DEFAULT-CAPE-GATEWARE]:[${version}]"
fi

if [ -f /proc/device-tree/chosen/overlays/PCIE-M2-GATEWARE ] ; then
	version=$(cat /proc/device-tree/chosen/overlays/PCIE-M2-GATEWARE | head -n1 || true)
	echo "UBOOT: Loaded Overlay:[PCIE-M2-GATEWARE]:[${version}]"
fi

if [ -f /usr/share/beagleboard/gateware/version.txt ] ; then
	version=$(cat /usr/share/beagleboard/gateware/version.txt | head -n1 || true)
	echo "SYSTEM: Gateware Version:[${version}]"
	pkg="bbb.io-gateware" ; dpkg_check_version
fi

pkg="bb-customizations" ; dpkg_check_version
pkg="bb-usb-gadgets" ; dpkg_check_version

if [ -d /home/ubuntu/ ] ; then
	echo "groups:[`groups ubuntu`]"
fi

if [ -d /home/beagle/ ] ; then
	echo "groups:[`groups beagle`]"
fi

echo "cmdline:[`cat /proc/cmdline`]"

echo "lsusb"
lsusb || true
echo "lspci"
lspci || true
echo "END"

#