#!/bin/sh -e

version="$1"

# passing the kernel version is required
if [ -z "${version}" ] ; then
	echo >&2 "W: zz-uenv_txt: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

device_model=$(cat /proc/device-tree/model | sed "s/ /_/g" | tr -d '\000')

if [ "x${device_model}" = "xBeagleBoard_BeagleV-Fire" ] ; then
	if [ -f /boot/firmware/boot.scr ] ; then
		if [ -f /boot/vmlinuz-${version} ] ; then
			rm -f /boot/firmware/mpfs-beaglev-fire.dtb || true
			echo "Updating: mpfs-beaglev-fire Device Tree"
			cp /usr/lib/linux-image-${version}/microchip/mpfs-beaglev-fire.dtb /boot/firmware/ || true
			cp /usr/lib/linux-image-${version}/microchip/mpfs-beaglev-fire.dtb /boot/ || true

			#Legacy
			if [ -f /boot/firmware/Image ] ; then
				rm -f /boot/firmware/Image || true
			fi

			echo "Updating: /boot/Image.gz"
			if [ -f /boot/Image ] ; then
				rm -f /boot/Image || true
			fi
			cat /boot/vmlinuz-${version} | gunzip -d > /boot/Image

			if [ -f /boot/Image.gz ] ; then
				rm -f /boot/Image.gz || true
			fi
			gzip -9 /boot/Image -c > /boot/Image.gz

			if [ -f /boot/firmware/Image.gz ] ; then
				rm -f /boot/firmware/Image.gz || true
			fi
			cp /boot/Image.gz /boot/firmware/Image.gz

			if [ -f /boot/mpfs-beaglev-fire.dtb ] ; then
				if [ -f /boot/Image.gz ] ; then
					echo "Updating: /boot/firmware/beaglev_fire.itb"
					if [ ! -f /boot/firmware/beaglev_fire.its ] ; then
						cp -v /etc/bbb.io/templates/beaglev_fire.its /boot/firmware/beaglev_fire.its
					fi
					if [ ! -f /boot/beaglev_fire.its ] ; then
						cp -v /etc/bbb.io/templates/beaglev_fire.its /boot/beaglev_fire.its
					fi

					cd /boot/
					mkimage -f beaglev_fire.its beaglev_fire.itb
					cd -

					if [ -f /boot/firmware/beaglev_fire.itb ] ; then
						rm -f /boot/firmware/beaglev_fire.itb || true
					fi
					cp -v /boot/beaglev_fire.itb /boot/firmware/beaglev_fire.itb
				fi
			fi

			echo "${version}" > /boot/firmware/kversion
			echo "zz-uenv_txt: Updated extlinux.conf /boot/firmware/ for: [${version}]"
		fi
	fi
fi
