#!/bin/bash

mkdir -p /dev/bone/pwm/

i=0
while [ $i -ne 16 ]
do
	unset pwm_node
	if [ -d /sys/class/pwm/pwmchip$i ] ; then
		pwm_node=$(udevadm info /sys/class/pwm/pwmchip$i/ | grep DEVPATH | awk -F 'fabric-bus@40000000/' '{print $2}' | awk -F '/' '{print $1}')
	fi

	case "${pwm_node}" in
	41400000.pwm)
		if [ -d /sys/class/pwm/pwmchip$i/pwm0/ ] ; then
			ln -sTf /sys/class/pwm/pwmchip$i/pwm0 /dev/bone/pwm/0/a
		fi
		if [ -d /sys/class/pwm/pwmchip$i/pwm1/ ] ; then
			ln -sTf /sys/class/pwm/pwmchip$i/pwm1/ /dev/bone/pwm/0/b
		fi
		;;
	41500000.pwm)
		if [ -d /sys/class/pwm/pwmchip$i/pwm0/ ] ; then
			ln -sTf /sys/class/pwm/pwmchip$i/pwm0 /dev/bone/pwm/1/a
		fi
		if [ -d /sys/class/pwm/pwmchip$i/pwm1/ ] ; then
			ln -sTf /sys/class/pwm/pwmchip$i/pwm1/ /dev/bone/pwm/1/b
		fi
		;;
	esac

	i=$(($i+1))
done

