#!/bin/bash -e

. version.sh

current_kernel () {
	if [ -f /tmp/LATEST-${var} ] ; then
		rm -rf /tmp/LATEST-${var} | true
	fi
	unset latest_kernel
	wget --quiet --directory-prefix=/tmp/ https://rcn-ee.net/repos/latest/${dist}-${arch}/LATEST-${var} || true
	if [ -f /tmp/LATEST-${var} ] ; then
		latest_kernel=$(cat "/tmp/LATEST-${var}" | grep "ABI:1 ${ver}" | awk '{print $3}')
		if [ ! "x${latest_kernel}" = "x" ] ; then
			echo ${dist}-${arch}-${latest_kernel}
		fi
	fi
}

generate_header () {
	echo "# This file is autogenerated. Do not edit!" > ./suite/${dist}/debian/${wfile}
	echo "Source: bbb.io-kernel" >> ./suite/${dist}/debian/${wfile}
	echo "Section: misc" >> ./suite/${dist}/debian/${wfile}
	echo "Priority: optional" >> ./suite/${dist}/debian/${wfile}
	echo "Maintainer: Robert Nelson <robertcnelson@gmail.com>" >> ./suite/${dist}/debian/${wfile}
	echo "Build-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " debhelper-compat (= ${debhelper})" >> ./suite/${dist}/debian/${wfile}
	echo "Standards-Version: 4.5.0" >> ./suite/${dist}/debian/${wfile}
	echo "Rules-Requires-Root: no" >> ./suite/${dist}/debian/${wfile}
	echo "" >> ./suite/${dist}/debian/${wfile}
	echo "Package: bbb.io-kernel-tasks" >> ./suite/${dist}/debian/${wfile}
	echo "Architecture: riscv64" >> ./suite/${dist}/debian/${wfile}
	echo "Pre-Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " generic-sys-mods" >> ./suite/${dist}/debian/${wfile}
	echo "Depends:" >> ./suite/${dist}/debian/${wfile}
	echo " tasksel" >> ./suite/${dist}/debian/${wfile}
	echo " , \${misc:Depends}" >> ./suite/${dist}/debian/${wfile}
	echo "Description: BeagleBoard.org Kernel Branches" >> ./suite/${dist}/debian/${wfile}
	echo " This package contains tasksel information for the BeagleBoard.org Kernel Branch." >> ./suite/${dist}/debian/${wfile}
}

generate_mainline_kernel () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: riscv64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org Mainline" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install Mainline in Debian." >> ./suite/${dist}/debian/${wfile}
	fi
}

generate_kernel_mpfs () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: riscv64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org ${msg}-riscv64 for mpfs-riscv64" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg}-riscv64 for in Debian." >> ./suite/${dist}/debian/${wfile}
	fi
}

generate_kernel_xuantie () {
	if [ ! "x${latest_kernel}" = "x" ] ; then
		echo "" >> ./suite/${dist}/debian/${wfile}
		echo "Package: bbb.io-kernel-${msg}" >> ./suite/${dist}/debian/${wfile}
		echo "Section: metapackages" >> ./suite/${dist}/debian/${wfile}
		echo "Architecture: riscv64" >> ./suite/${dist}/debian/${wfile}
		echo "Pre-Depends: linux-image-${latest_kernel}" >> ./suite/${dist}/debian/${wfile}
		echo "Depends: \${misc:Depends}, bbb.io-kernel-tasks (= \${source:Version})" >> ./suite/${dist}/debian/${wfile}
		echo "Description: BeagleBoard.org ${msg}-riscv64 for xuantie-riscv64" >> ./suite/${dist}/debian/${wfile}
		echo " This metapackage will install linux-image-${msg}-riscv64 for in Debian." >> ./suite/${dist}/debian/${wfile}
	fi
}

changelog () {
	git diff ./suite/${dist}/debian/control > /tmp/changelog-readme.diff
	cat /tmp/changelog-readme.diff | grep +Pre-Depends: | awk '{print $2}' | awk -F ',' '{print $1}' > /tmp/changelog-readme.cat
	sort -u /tmp/changelog-readme.cat > /tmp/changelog-readme.sort
	echo "  * Kernel Updates" > suite/${dist}/readme.log
	ts "  *" /tmp/changelog-readme.sort >> suite/${dist}/readme.log
	cat suite/${dist}/readme.log
}

do_trixie () {
	#13.x
	arch="riscv64"
	dist="trixie"
	debhelper="13"
	wfile="control"
	generate_header

	msg="mainline"    ; var="riscv64"         ; ver="STABLE" ; current_kernel ; generate_mainline_kernel
#	msg="6.1-mpfs"    ; var="mpfs-riscv64"    ; ver="LTS61X" ; current_kernel ; generate_kernel_mpfs
	msg="6.6-mpfs"    ; var="mpfs-riscv64"    ; ver="LTS66X" ; current_kernel ; generate_kernel_mpfs
#	msg="6.6-xuantie" ; var="xuantie-riscv64" ; ver="LTS66X" ; current_kernel ; generate_kernel_xuantie

	changelog
}

do_noble () {
	#24.04
	arch="riscv64"
	dist="noble"
	debhelper="13"
	wfile="control"
	generate_header

	msg="mainline"    ; var="riscv64"         ; ver="STABLE" ; current_kernel ; generate_mainline_kernel
	msg="6.1-mpfs"    ; var="mpfs-riscv64"    ; ver="LTS61X" ; current_kernel ; generate_kernel_mpfs
	msg="6.6-mpfs"    ; var="mpfs-riscv64"    ; ver="LTS66X" ; current_kernel ; generate_kernel_mpfs
	msg="6.6-xuantie" ; var="xuantie-riscv64" ; ver="LTS66X" ; current_kernel ; generate_kernel_xuantie

	changelog
}

do_trixie
do_noble

